#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    interstate-8-5-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^interstate-8-5\.ddev\.site$`)
      
      service: "interstate-8-5-web-80"
      tls: false
      # middlewares:
      #   - "interstate-8-5-redirectHttps"
    interstate-8-5-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^interstate-8-5\.ddev\.site$`)
      
      service: "interstate-8-5-web-8025"
      tls: false
      # middlewares:
      #   - "interstate-8-5-redirectHttps"
    interstate-8-5-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^interstate-8-5\.ddev\.site$`)
      
      service: "interstate-8-5-xhgui-80"
      tls: false
      # middlewares:
      #   - "interstate-8-5-redirectHttps"
    
    
    
    interstate-8-5-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^interstate-8-5\.ddev\.site$`)
      
      service: "interstate-8-5-web-80"
      
      tls: true
      
    interstate-8-5-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^interstate-8-5\.ddev\.site$`)
      
      service: "interstate-8-5-web-8025"
      
      tls: true
      
    
    interstate-8-5-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^interstate-8-5\.ddev\.site$`)
      
      service: "interstate-8-5-xhgui-80"
      
      tls: true
      
    

  middlewares:
    interstate-8-5-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    interstate-8-5-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-interstate-8-5-web:80
        
    interstate-8-5-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-interstate-8-5-web:8025
        
    
    
    interstate-8-5-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-interstate-8-5-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/interstate-8-5.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/interstate-8-5.key